FROM node:22-alpine AS builder

WORKDIR /app
COPY ["./package*.json", "./"]

RUN npm install
COPY [".", "./"]
RUN npm run build

FROM nginx:1.27.3-alpine

COPY --from=builder ["/app/dist/", "/user/share/nginx/html/"]
COPY --from=builder ["/app/nginx.conf", "/etc/nginx/nginx.conf"]

EXPOSE 80 443

CMD ["/usr/sbin/nginx", "-g", "daemon off;"]

# docker buildx build -t portfolio_img:v1 -f Dockerfile.prod .
# docker run --name portfolio -itd -p 80:80 -p 443:443 portfolio_img:v1
